<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><title>School Essentials | Form Factory.</title><meta name="google-site-verification" content="liGddaK7I8_x0tSdKv36CRi_rMfRt3yMNjILkbOAxxY" /><link href='http://feeds2.feedburner.com/webinfopedia' rel='alternate' title='Webinfopedia-Learn SEO, Web Designing and Web development easily with example and demos' type='application/rss+xml'/><meta name="msvalidate.01" content="1CBFD6FA96646CD69CE09C869B2F6313" /><META name="y_key" content="2e447c925218040f" /><link rel="search" type="application/opensearchdescription+xml" href="http://www.webinfopedia.com/classes/opensearch.xml" title="SEO,PHP and Ajax blog" /> <meta content="Learn how to create zip and download multiple files using PHP. Multiple file download script in PHP and download files from database by making it rar" name="description"  /><meta content="zip,rar,php,make rar,create rar,php rar,php zip,php rar,download script,download file,make rar,rar script,download script,php script,rar makinf script,make rar online" name="keywords"  /><meta name="author" content="webinfopedia" /><meta name="copyright" content="webinfopedia.com" /><meta name="Robots" content="index, follow" /><meta name="language" content="English" /><link rel="shortcut icon" href="http://www.webinfopedia.com/images/webinfopedia-fav.png"  /><script type="text/javascript">  var _gaq = _gaq || [];  _gaq.push(['_setAccount', 'UA-22897853-1']);  _gaq.push(['_trackPageview']);  (function() {    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);  })();</script><style type="text/css">body,td,th {	font-family: Georgia,"Times New Roman",Times,serif;;	font-size: 12px;	color: #333;}ody {	margin-left: 0px;	margin-top: 30px;	margin-right: 0px;	margin-bottom: 0px;}.maindiv{ width:690px; margin:0 auto; padding:20px; background:#CCC;}.innerbg{ padding:6px; background:#FFF;}.links{ font-weight:bold; color:#c24f00; text-decoration:none; font-size:12px;}--></style></head><body><div style="text-align:center;">
  <h1 style="color:#666;">School Essentials <a href="#" style="color:#EEDDCA; text-decoration:none; font-size:18px;">timetable samples</a></h1></div>  <div style="width:730px; margin:0 auto;">  </div><div class="maindiv"><div class="innerbg"><table width="100%" border="0" cellpadding="2" cellspacing="2">  <tr>
    <td align="left" valign="middle" bgcolor="#008000"><div style="margin:0px 10px; font-weight:bold; color:#FFF; font-size:16px;">Please select the sample you wish to download.</div></td></tr>  <tr>    <td align="center" valign="middle"><table width="100%" border="0" cellspacing="2" cellpadding="2">      <tr>        <td width="60%" align="left" valign="middle"><div style="margin:0 auto; padding:8px 4px; text-align:center; width:328px;">
    
    <table width="100%" border="0" cellspacing="4" cellpadding="4">  
    
    <tr>    <td width="9%" align="left" valign="middle"><img src="files/tick.jpg" width="16" height="16" /></td>    <td width="91%" align="left" valign="middle"><a href="download.php?filename=composite_tt.pdf" class="links">Download composite timetable.pdf</a></td>  </tr> 
    
     <tr>    <td align="left" valign="middle"><img src="files/tick.jpg" width="16" height="16" /></td>    <td align="left" valign="middle"><a href="download.php?filename=composite_by_educator.pdf" class="links">Download composite by educator.pdf</a></td>  </tr> 
     
      <tr>    <td align="left" valign="middle"><img src="files/tick.jpg" width="16" height="16" /></td>    <td align="left" valign="middle"><a href="download.php?filename=composite_by_learning_area.pdf" class="links">Download composite by learning area.pdf</a></td>  </tr> 
      
       <tr>    <td align="left" valign="middle"><img src="files/tick.jpg" alt="" width="16" height="16" /></td>    <td align="left" valign="middle"><a href="download.php?filename=grade_tt.pdf" class="links">Download grade timetable.pdf</a></td>  </tr> 
       
       <tr>    <td align="left" valign="middle"><img src="files/tick.jpg" alt="" width="16" height="16" /></td>    <td align="left" valign="middle"><a href="download.php?filename=class_tt.pdf" class="links">Download class/learner timetable.pdf</a></td>  </tr>
       
       <tr>    <td align="left" valign="middle"><img src="files/tick.jpg" alt="" width="16" height="16" /></td>    <td align="left" valign="middle"><a href="download.php?filename=educator_tt.pdf" class="links">Download educator timetable.pdf</a></td>  </tr>

       <tr>    <td align="left" valign="middle"><img src="files/tick.jpg" alt="" width="16" height="16" /></td>    <td align="left" valign="middle"><a href="download.php?filename=relief_tt.pdf" class="links">Download relief timetable.pdf</a></td>  </tr>

        <tr>    <td align="left" valign="middle"><img src="files/tick.jpg" alt="" width="16" height="16" /></td>    <td align="left" valign="middle"><a href="download.php?filename=educator_workload.pdf" class="links">Download edutator workload.pdf</a></td>  </tr>
  
     </table></td>   
    
       
      <td width="40%" align="left" valign="middle"><img src="images/logo.png" width="273" height="84" /></td>      </tr>    </table></td>    </tr></table></div></div><div style="width:730px; margin:0 auto; padding:8px 0px;"></div></body></html>